### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by markdicks**
I've improved some text inside the readme as well as correct the format of it. Please note that readme was the only file changed. The description will need to be added by yourself related to #1

### CODE REVIEW

**Comment by VenusChappie** [comment]
Thank you so much Mark. I was actually going to create a script that installs all the dependencies needed for the project and then update the readme. But I honestly appreciate your help. Thanks again

**Comment by markdicks** [comment]
No stress, if you would like me to work on the script let me know. If you have any other projects/tasks I'd be glad to help

**Comment by VenusChappie** [comment]
Hey Mark, 

Sorry for getting back to you so late, we have a huge showcase happening tomorrow so you can imagine how hectic our deadlines were this week. 

I would honestly appreciate you helping me out with the script. I'm swamped with work at the moment and could use that helping hand with this project. Thank you. Let me send you the list of packages that need to be included in the script and you'll let me know if you're still keen.

**Comment by markdicks** [comment]
Yeah 100%. Still keen. I understand the deadline situation lmao.

You can create the `requirements.txt` file and I will correct it if correction is needed and then complete the script.

**Pull request merged**
